package com.aktv.project.giangdien.data.criteria;

import java.util.ArrayList;
import java.util.List;

/**
 * AbstractCriteria -
 *
 * @author thinhnguyen <hung-thinh.nguyen-thai@fullsix.com>
 */
public abstract class AbstractCriteria {

    protected String orderByClause;

    protected boolean distinct;

    protected List<CategoryCriteria.Criteria> oredCriteria;

    public AbstractCriteria() {
        oredCriteria = new ArrayList<CategoryCriteria.Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<CategoryCriteria.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(CategoryCriteria.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public CategoryCriteria.Criteria or() {
        CategoryCriteria.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Sep 20 18:55:49 ICT 2016
     */
    public CategoryCriteria.Criteria createCriteria() {
        CategoryCriteria.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Sep 20 18:55:49 ICT 2016
     */
    protected CategoryCriteria.Criteria createCriteriaInternal() {
        CategoryCriteria.Criteria criteria = new CategoryCriteria.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Sep 20 18:55:49 ICT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }
}
